import assert from "node:assert/strict";
import test, { after } from "node:test";
import { createServer } from "vite";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const vite = await createServer({ appType: "custom", configFile: false, root, resolve: { alias: { "@": root } }, server: { middlewareMode: true } });
after(async () => vite.close());
const { resolvePatrimonyOutcome } = await vite.ssrLoadModule("/data/patrimonio.ts");

const theft = (cuantia = 100, extra = {}, process = {}, relational = {}) => resolvePatrimonyOutcome({ hechoPrincipal: "apoderamiento", titularidad: "ajena", gradoEjecucion: "consumado", intencionApropiacionBeneficio: true, sinConsentimiento: true, violenciaFisica: false, intimidacion: false, fuerza: "ninguna", cuantia, cuantiaAcreditada: true, ...extra }, process, relational);
const force = (extra = {}, process = {}) => resolvePatrimonyOutcome({ hechoPrincipal: "apoderamiento", titularidad: "ajena", gradoEjecucion: "consumado", intencionApropiacionBeneficio: true, sinConsentimiento: true, violenciaFisica: false, intimidacion: false, fuerza: "fractura_contenedor", tipoLugar: "otro", cuantia: 50, cuantiaAcreditada: true, ...extra }, process);
const violence = (extra = {}, process = {}, relational = {}) => resolvePatrimonyOutcome({ hechoPrincipal: "apoderamiento", titularidad: "ajena", gradoEjecucion: "consumado", intencionApropiacionBeneficio: true, sinConsentimiento: true, violenciaFisica: false, intimidacion: true, momentoViolencia: "apoderamiento", conexionViolenciaApoderamiento: true, ...extra }, process, relational);
const appropriation = (cuantia, extra = {}) => resolvePatrimonyOutcome({ hechoPrincipal: "recepcion", titularidad: "ajena", posesionPrevia: "autor_entrega_legitima", gradoEjecucion: "consumado", recepcionLegitima: true, obligacionDevolverEntregar: true, conductaApropiacionONegacion: true, cuantia, cuantiaAcreditada: true, ...extra });
const damage = (cuantia, extra = {}) => resolvePatrimonyOutcome({ hechoPrincipal: "danos", titularidad: "ajena", intencionalidadDano: "deliberado", cuantia, cuantiaAcreditada: true, ...extra });

test("1 · hurto 399 €: 234.2, leve y art. 495", () => { const o=theft(399); assert.match(o.norma,/234\.2/); assert.equal(o.gravedad,"DELITO LEVE"); assert.equal(o.procesal.escenarioProcesal,"DELITO LEVE"); });
test("2 · hurto exactamente 400 € sigue leve", () => assert.equal(theft(400).gravedad,"DELITO LEVE"));
test("3 · hurto 401 €: 234.1 menos grave", () => { const o=theft(401); assert.match(o.norma,/234\.1/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("4 · antihurto neutralizado activa 234.3 sin crear robo", () => { const o=theft(100,{dispositivoAntihurtoEnCosaNeutralizado:true}); assert.match(o.norma,/234\.3/); assert.match(o.resultado,/HURTO/); });
test("5 · teléfono particular 300 € activa 235.1.10", () => { const o=theft(300,{telefonoODispositivo235:true,existenciaComercialVentaAlmacenExposicion:false}); assert.match(o.norma,/235/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("6 · teléfono comercial no activa 235.1.10", () => assert.match(theft(300,{telefonoODispositivo235:true,existenciaComercialVentaAlmacenExposicion:true}).norma,/234\.2/));
test("7 · bien histórico de 100 € activa 235", () => assert.match(theft(100,{valorArtisticoHistoricoCulturalCientifico:true}).norma,/235/));
test("8 · tres condenas ejecutorias completas elevan hurto leve", () => { const o=theft(100,{estadoCondenasPrevias:"condenas_ejecutorias_verificadas",numeroCondenasEjecutorias:3,condenasMismaNaturaleza:true,algunaCondenaLeve:true,condenasCanceladasOCancelables:false,requisitosCondenasCompletos:true}); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
for (const [n,state] of [[9,"tres denuncias"],[10,"tres detenciones"],[11,"antecedentes policiales"]]) test(`${n} · ${state} no son multirreincidencia`, () => assert.equal(theft(100,{estadoCondenasPrevias:"antecedentes_no_judicialmente_verificados"}).gravedad,"DELITO LEVE"));
test("12 · sin información judicial no bloquea", () => assert.equal(theft(100).estado,"resuelto"));
test("13 · pasar a condenas verificadas recalcula", () => { assert.equal(theft(100).gravedad,"DELITO LEVE"); assert.equal(theft(100,{estadoCondenasPrevias:"condenas_ejecutorias_verificadas",numeroCondenasEjecutorias:3,condenasMismaNaturaleza:true,algunaCondenaLeve:true,condenasCanceladasOCancelables:false,requisitosCondenasCompletos:true}).gravedad,"DELITO MENOS GRAVE"); });
test("14 · volver a no verificado elimina agravación", () => assert.equal(theft(100,{estadoCondenasPrevias:"no_consta_verificacion"}).gravedad,"DELITO LEVE"));
test("15 · vitrina cerrada forzada es robo con fuerza", () => { const o=force(); assert.match(o.norma,/238.*240/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("16 · fuerza para abandonar mantiene arts. 237/238", () => assert.match(force({fuerzaParaAccederOAbandonar:true}).norma,/237, 238/));
test("17 · llave sustraída usada es fuerza", () => assert.match(force({fuerza:"llave_falsa"}).resultado,/ROBO CON FUERZA/));
test("18 · morada temporalmente vacía aplica 241.1", () => assert.match(force({tipoLugar:"morada"}).norma,/241\.1/));
test("19 · 241.4 clasifica grave", () => { const o=force({tipoLugar:"morada",especialGravedad2414:true}); assert.match(o.norma,/241\.4/); assert.equal(o.gravedad,"DELITO GRAVE"); });
test("20 · 241.4 no flagrante sin riesgo no automatiza detención", () => assert.equal(force({tipoLugar:"morada",especialGravedad2414:true},{flagrante:false,indiciosHechoSuficientes:true,indiciosParticipacionSuficientes:true}).procesal.detencion,"NO"));
test("21 · 241.4 no flagrante con riesgo concreto permite detener", () => assert.equal(force({tipoLugar:"morada",especialGravedad2414:true},{flagrante:false,indiciosHechoSuficientes:true,indiciosParticipacionSuficientes:true,intentoFugaElusion:true}).procesal.detencion,"SÍ"));
test("22 · intimidación para sustraer 20 € es art. 242", () => { const o=violence({cuantia:20,cuantiaAcreditada:true}); assert.match(o.norma,/242/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("23 · violencia en huida recalcula a robo", () => assert.match(violence({momentoViolencia:"huida"}).resultado,/ROBO/));
test("24 · uso efectivo de arma activa 242.3", () => assert.match(violence({armaPresente:true,armaUsada:true}).norma,/242\.3/));
test("25 · mera tenencia de arma no activa 242.3", () => assert.doesNotMatch(violence({armaPresente:true,armaUsada:false}).norma,/242\.3/));
test("26 · apropiación 300 € es 253.2 leve", () => { const o=appropriation(300); assert.match(o.norma,/253\.2/); assert.equal(o.gravedad,"DELITO LEVE"); });
test("27 · apropiación 1.000 € es 253.1 menos grave", () => { const o=appropriation(1000); assert.match(o.norma,/253\.1/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("28 · apropiación con agravación 250 usa marco grave", () => { const o=appropriation(1000,{agravacion250Acreditada:true}); assert.match(o.norma,/250/); assert.equal(o.gravedad,"DELITO GRAVE"); });
test("29 · art. 254 ordinario 500 € es leve por 13.4", () => { const o=resolvePatrimonyOutcome({hechoPrincipal:"recepcion",titularidad:"ajena",posesionPrevia:"tercero",gradoEjecucion:"consumado",viaApropiacionFuera253:true,cuantia:500,cuantiaAcreditada:true}); assert.match(o.norma,/254\.1/); assert.equal(o.gravedad,"DELITO LEVE"); });
test("30 · art. 254 cultural es menos grave", () => assert.equal(resolvePatrimonyOutcome({hechoPrincipal:"recepcion",titularidad:"ajena",posesionPrevia:"tercero",gradoEjecucion:"consumado",viaApropiacionFuera253:true,cuantia:100,cuantiaAcreditada:true,valorArtisticoHistoricoCulturalCientifico:true}).gravedad,"DELITO MENOS GRAVE"));
test("31 · empleado con mero acceso no se presume 253", () => assert.match(resolvePatrimonyOutcome({hechoPrincipal:"recepcion",titularidad:"ajena",posesionPrevia:"autor_acceso_material",gradoEjecucion:"consumado",conductaApropiacionONegacion:true,cuantia:100,cuantiaAcreditada:true}).norma,/234/));
test("32 · empleado con custodia y devolución puede ser 253", () => assert.match(appropriation(100,{relacionLaboralProfesional:true}).norma,/253/));
test("33 · facultades excedidas derivan a 252", () => assert.match(resolvePatrimonyOutcome({hechoPrincipal:"recepcion",titularidad:"ajena",posesionPrevia:"autor_facultades_administracion",gradoEjecucion:"consumado",facultadesAdministracion:true,excesoFacultadesConPerjuicio:true,cuantia:1000,cuantiaAcreditada:true}).norma,/252/));
test("34 · daño privado 300 € es leve", () => assert.equal(damage(300).gravedad,"DELITO LEVE"));
test("35 · daño privado 500 € es menos grave", () => assert.equal(damage(500).gravedad,"DELITO MENOS GRAVE"));
test("36 · daño a bien de uso público activa 263.2", () => { const o=damage(100,{bienDominioUsoPublicoComunal:true}); assert.match(o.norma,/263\.2/); assert.equal(o.gravedad,"DELITO MENOS GRAVE"); });
test("37 · daño accidental 5.000 € no activa 263", () => assert.doesNotMatch(damage(5000,{intencionalidadDano:"imprudente_accidental",imprudenciaGrave:false}).norma,/263/));
test("38 · imprudencia grave superior a 80.000 € activa 267", () => assert.match(damage(80001,{intencionalidadDano:"imprudente_accidental",imprudenciaGrave:true}).norma,/267/));
test("39 · cónyuges no separados sin violencia muestran art. 268", () => assert.match(theft(100,{separacionConyugal:false,procesoSeparacionDivorcioNulidad:false},{},{tipoRelacion:"esposa"}).exencion.titulo,/268/));
test("40 · violencia excluye art. 268", () => assert.equal(violence({separacionConyugal:false,procesoSeparacionDivorcioNulidad:false},{},{tipoRelacion:"esposa"}).exencion,undefined));
test("41 · art. 268 no se extiende al tercero extraño", () => assert.match(theft(100,{separacionConyugal:false,procesoSeparacionDivorcioNulidad:false,terceroExtranoParticipa:true},{},{tipoRelacion:"esposa"}).exencion.fundamento,/tercero extraño/));
test("42 · titularidad compartida no cierra tipo", () => assert.equal(theft(100,{titularidad:"compartida"}).estado,"pendiente"));
test("43 · robo con fuerza en tentativa conserva ambos", () => { const o=force({gradoEjecucion:"tentativa"}); assert.match(o.resultado,/ROBO/); assert.match(o.grado,/TENTATIVA/); });
test("44 · tentativa patrimonial leve conserva art. 495", () => assert.equal(theft(100,{gradoEjecucion:"tentativa"}).procesal.escenarioProcesal,"DELITO LEVE"));
test("45 · tres episodios sin nexo no crean continuado", () => assert.match(theft(100,{numeroEpisodios:3,nexoPlanOcasionComunAcreditado:false}).avisos.join(" "),/NO PUEDE DETERMINARSE/));
test("46 · cambiar 399 a 401 recalcula gravedad y proceso", () => { assert.equal(theft(399).gravedad,"DELITO LEVE"); assert.equal(theft(401).gravedad,"DELITO MENOS GRAVE"); });
test("47 · cambiar sin violencia a violencia de huida recalcula hurto a robo", () => { assert.match(theft(20).resultado,/HURTO/); assert.match(violence({momentoViolencia:"huida"}).resultado,/ROBO/); });
test("48 · cambiar recepción legítima a mero acceso recalcula 253 a 234", () => { assert.match(appropriation(100).norma,/253/); assert.match(resolvePatrimonyOutcome({hechoPrincipal:"recepcion",titularidad:"ajena",posesionPrevia:"autor_acceso_material",gradoEjecucion:"consumado",conductaApropiacionONegacion:true,cuantia:100,cuantiaAcreditada:true}).norma,/234/); });
test("49 · separación elimina excusa del art. 268", () => assert.equal(theft(100,{separacionConyugal:true,procesoSeparacionDivorcioNulidad:false},{},{tipoRelacion:"esposa"}).exencion,undefined));
test("50 · cambiar hecho principal no conserva estado de la rama previa", () => { const a=theft(100); const b=damage(500); assert.notEqual(a.tipoPenal,b.tipoPenal); assert.doesNotMatch(b.norma,/234/); });
