"use client";
import "./conditional.css";
import "./penal.css";
import "./itv.css";
import "./alcoholemia.css";
import "./seguridad-publica.css";
import "./seguridad-publica-ux.css";
import { useMemo, useState } from "react";
import { modules } from "@/data/modules";
import { categories } from "@/data/categories";
import { cases } from "@/data/cases";
import { rules } from "@/data/rules";
import { resolveCaseSources } from "@/data/sources";
import { visibleOperationalWarnings } from "@/data/warnings";
import { resolveValidatedPenalPrecept } from "@/data/penal";
import { containsInternalInterfaceLanguage, visibleTextList } from "@/data/visibility";
import { resolveMeasures } from "@/data/itv";
import { PermitCaseSheet } from "./permit-case-sheet";
import { PermitCategoryView, PermitGroupView } from "./permit-navigation";
import { permisosGroups } from "@/data/permisos";
import { libraryDocuments } from "@/data/documents";
import { publicPath } from "@/lib/public-path";
import { AlcoholemiaView } from "./alcoholemia";
import { SeguridadPublicaView } from "./seguridad-publica";
import { seguridadPublicaBlockFromCategoryId, seguridadPublicaBlockLabel, seguridadPublicaSearchEntries } from "@/data/seguridad-publica";
import type { ConditionalPenalRelevance, OperationalCase, PenalPrecept, PermitOperationalCase, TrafficMeasurePlan } from "@/data/types";
type View = { moduleId?: string; categoryId?: string; permitGroupId?: string; caseId?: string; securityPublicConceptId?: string; library?: boolean };
const euro = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export default function Home() {
  const [view, setView] = useState<View>({}); const [query, setQuery] = useState(""); const [copied, setCopied] = useState(false);
  const validCases = useMemo(() => cases.filter((item) => item.estado === "validado"), []);
  const selectedModule = modules.find((item) => item.id === view.moduleId); const selectedCategory = categories.find((item) => item.id === view.categoryId); const selectedPermitGroup = permisosGroups.find((item) => item.id === view.permitGroupId); const selectedCase = validCases.find((item) => item.id === view.caseId);
  const results = useMemo(() => { const q = normalize(query.trim()); if (!q) return []; const caseResults = validCases.filter((item) => normalize([item.titulo, ...item.palabras_clave, item.modulo, item.categoria, item.norma, item.articulo].join(" ")).includes(q)).map((item) => ({ kind: "case" as const, item })); const publicResults = seguridadPublicaSearchEntries.filter((item) => normalize([item.titulo, ...item.sinonimos, item.bloque].join(" ")).includes(q)).map((item) => ({ kind: "security-public" as const, item })); return [...caseResults, ...publicResults]; }, [query, validCases]);
  const openCase = (item: OperationalCase) => { const permitGroupId = (item as PermitOperationalCase).subgrupo; setView({ moduleId: item.modulo, categoryId: item.categoria, permitGroupId, caseId: item.id }); setQuery(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const goBack = () => setView(view.library ? {} : selectedCase ? { moduleId: view.moduleId, categoryId: view.categoryId, permitGroupId: (selectedCase as PermitOperationalCase).subgrupo } : selectedPermitGroup ? { moduleId: view.moduleId, categoryId: view.categoryId } : selectedCategory ? { moduleId: view.moduleId } : {});
  const copySummary = async (item: OperationalCase) => { const amount = item.importe_fijo != null ? `${item.calificacion}: ${euro.format(item.importe_fijo)} (${euro.format(item.importe_reducido ?? 0)} con reducción)` : item.rango_min != null && item.rango_max != null ? `${item.calificacion}: ${euro.format(item.rango_min)} – ${euro.format(item.rango_max)}` : item.calificacion ?? "Sin cuantía cerrada"; const norm = item.norma_infringida && item.articulo_infringido ? `${item.norma_infringida} — art. ${item.articulo_infringido}` : `${item.norma} — art. ${item.articulo}`; const text = `${item.titulo}\n${item.resultado}\n${norm}\n${item.tipificacion_norma && item.tipificacion_articulo ? `Tipificación: ${item.tipificacion_norma} — art. ${item.tipificacion_articulo}\n` : ""}${item.textoDenuncia ? `Texto para el boletín: ${item.textoDenuncia}\n` : ""}${item.codificado ? `Codificado: ${item.codificado}\n` : ""}${amount}\n${item.inmovilizacion ? `Inmovilización: ${item.inmovilizacion}. ${item.motivo_inmovilizacion ?? ""}\n` : ""}Actuación: ${visibleTextList(item.actuacion_breve ?? item.actuacion).join(" ")}\nÓrgano actuante: ${item.competencia_denuncia}\nÓrgano sancionador: ${item.competencia_resuelve}`; await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <main><header className="topbar"><div className="brandmark">BO</div><div><span className="eyebrow">VERSIÓN 0.6.0</span><h1>Base Operativa <span>Policía Local</span></h1></div><button className="library-link" onClick={() => { setView({ library: true }); setQuery(""); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Biblioteca documental</button></header><div className="shell">
    {(selectedModule || selectedCategory || selectedCase || view.library) && <button className="back" onClick={goBack}>← Volver a la Base Operativa</button>}
    {!selectedCase && !view.library && <section className="searchbox"><label htmlFor="search">Consulta rápida</label><div className="searchrow"><span>⌕</span><input id="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por caso, palabra clave, norma o artículo…" autoComplete="off" />{query && <button onClick={() => setQuery("")} aria-label="Borrar búsqueda">×</button>}</div>{query && <div className="results"><p>{results.length ? `${results.length} resultado${results.length > 1 ? "s" : ""}` : "No hay casos validados que coincidan"}</p>{results.map((result) => <button key={`${result.kind}-${result.item.id}`} onClick={() => result.kind === "case" ? openCase(result.item) : (setView({ moduleId: "seguridad_publica", categoryId: result.item.categoria, securityPublicConceptId: result.item.id }), setQuery(""), window.scrollTo({ top: 0, behavior: "smooth" }))}><span><strong>{result.item.titulo}</strong><small>{result.kind === "case" ? `${modules.find((m) => m.id === result.item.modulo)?.nombre} · ${categories.find((c) => c.id === result.item.categoria)?.nombre}` : `Seguridad Pública · ${seguridadPublicaBlockLabel(result.item.bloque)}`}</small></span><b>›</b></button>)}</div>}</section>}
    {view.library && <LibraryView onBack={goBack} />}
    {!selectedModule && !query && !view.library && <section><div className="intro"><p>Selecciona un ámbito de actuación</p><span>El contenido se genera desde una base común de datos estructurados.</span></div><div className="modulegrid">{modules.filter((m) => m.activo).sort((a,b) => a.orden-b.orden).map((m, i) => { const count = m.id === "seguridad_publica" ? seguridadPublicaSearchEntries.length : validCases.filter((c) => c.modulo === m.id).length; return <button className="modulecard" key={m.id} onClick={() => setView({ moduleId: m.id })}><span className={`moduleicon tone-${i}`}>{["◉","◇","▥","⬡"][i]}</span><span><strong>{m.nombre}</strong><small>{m.descripcion}</small><em>{count ? `${count} ${m.id === "seguridad_publica" ? "conceptos operativos" : "casos disponibles"}` : "Contenido en desarrollo"}</em></span><b>›</b></button>})}</div></section>}
    {selectedModule && !selectedCategory && <section><div className="sectionhead"><span className="kicker">MÓDULO</span><h2>{selectedModule.nombre}</h2><p>{selectedModule.descripcion}</p></div>{categories.some((c) => c.modulo === selectedModule.id && c.activo) ? <div className="listcards">{categories.filter((c) => c.modulo === selectedModule.id && c.activo).sort((a,b) => a.orden-b.orden).map((c) => { const count = validCases.filter((item) => item.categoria === c.id).length; const isTool = c.id === "seguridad_vial_alcoholemia" || c.id.startsWith("seguridad_publica_"); return <button key={c.id} onClick={() => setView({ moduleId: selectedModule.id, categoryId: c.id })}><span><strong>{c.nombre}</strong><small>{c.descripcion}</small></span><em>{isTool ? "Herramienta operativa" : `${count} ${count === 1 ? "caso" : "casos"}`}</em><b>›</b></button>})}</div> : <Empty text="La arquitectura del módulo ya está preparada para incorporar categorías y casos validados." />}</section>}
    {selectedCategory && !selectedCase && !selectedPermitGroup && (selectedCategory.id === "seguridad_vial_permisos" ? <PermitCategoryView category={selectedCategory} cases={validCases.filter((item) => item.categoria === selectedCategory.id) as PermitOperationalCase[]} groups={permisosGroups} onOpenCase={openCase} onOpenGroup={(group) => { setView({ moduleId: selectedModule?.id, categoryId: selectedCategory.id, permitGroupId: group.id }); window.scrollTo({ top: 0, behavior: "smooth" }); }} /> : selectedCategory.id === "seguridad_vial_alcoholemia" ? <AlcoholemiaView onBack={goBack} /> : seguridadPublicaBlockFromCategoryId(selectedCategory.id) ? <SeguridadPublicaView key={`${selectedCategory.id}-${view.securityPublicConceptId ?? "overview"}`} block={seguridadPublicaBlockFromCategoryId(selectedCategory.id)!} initialConceptId={view.securityPublicConceptId} onBack={goBack} /> : <section><div className="sectionhead"><span className="kicker">{selectedModule?.nombre}</span><h2>{selectedCategory.nombre}</h2><p>{selectedCategory.descripcion}</p></div><div className="listcards">{validCases.filter((item) => item.categoria === selectedCategory.id).map((item) => <button key={item.id} onClick={() => openCase(item)}><span><strong>{item.titulo}</strong><small>{item.norma} · art. {item.articulo}</small></span>{item.alerta_penal && <em className="warningtag">Atención penal</em>}<b>›</b></button>)}</div>{!validCases.some((item) => item.categoria === selectedCategory.id) && <Empty title="Sin casos validados" text="Los casos en borrador, revisión o bloqueados no se muestran como utilizables." />}</section>)}
    {selectedPermitGroup && !selectedCase && <PermitGroupView group={selectedPermitGroup} cases={validCases.filter((item) => item.categoria === "seguridad_vial_permisos") as PermitOperationalCase[]} onOpenCase={openCase} />}
    {selectedCase && <CaseSheet key={selectedCase.id} item={selectedCase} copied={copied} onCopy={() => copySummary(selectedCase)} />}
  </div><footer><strong>Herramienta de apoyo.</strong> Verificar siempre la normativa vigente y las circunstancias concretas.</footer></main>;
}
function Empty({ title="Contenido en desarrollo", text }: { title?: string; text: string }) { return <div className="empty"><h3>{title}</h3><p>{text}</p></div> }
function LibraryView({ onBack }: { onBack: () => void }) {
  const [query, setQuery] = useState("");
  const results = useMemo(() => { const q = normalize(query.trim()); return q ? libraryDocuments.filter((document) => normalize(`${document.titulo} ${document.archivo} ${document.descripcion}`).includes(q)) : libraryDocuments; }, [query]);
  return <section className="library-view"><div className="sectionhead"><span className="kicker">CONSULTA DOCUMENTAL</span><h2>Biblioteca documental</h2><p>{libraryDocuments.length} documentos disponibles para consulta. Esta biblioteca no incorpora automáticamente documentos como fuentes jurídicas del motor.</p></div><div className="library-search"><label htmlFor="document-search">Buscar documentos</label><input id="document-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por título o nombre de archivo…" autoComplete="off" /></div><div className="library-list">{results.map((document) => <article key={document.archivo}><div><strong>{document.titulo}</strong><p>{document.descripcion}</p><small>{document.archivo}</small></div><a href={encodeURI(publicPath(`/documentos/${document.archivo}`))} target="_blank" rel="noreferrer">Abrir PDF <span aria-hidden="true">↗</span></a></article>)}</div>{!results.length && <Empty title="Sin resultados" text="No hay documentos que coincidan con la búsqueda." />}<button className="back library-back" onClick={onBack}>← Volver a la Base Operativa</button></section>
}
export function CaseSheet(props: { item: OperationalCase; copied: boolean; onCopy: () => void }) { return props.item.categoria === "seguridad_vial_permisos" ? <PermitCaseSheet {...props} /> : props.item.modulo === "seguridad_vial" ? <TrafficCaseSheet {...props} /> : <LegacyCaseSheet {...props} /> }
function LegacyCaseSheet({ item, copied, onCopy }: { item: OperationalCase; copied: boolean; onCopy: () => void }) { const [conditionalPenalActive, setConditionalPenalActive] = useState(false); const rule = rules.find((r) => r.id === item.regla_transversal && r.activo); const linkedSources = resolveCaseSources(item.fuentes); const linkedMeasures = resolveMeasures(item.medidas); const visibleWarnings = visibleOperationalWarnings(item); const conditionalFit = item.datos_adicionales?.encaje_condicional; const conditionalClassification = item.datos_adicionales?.calificacion_condicional; const conditionalPenal = item.datos_adicionales?.relevancia_penal_condicional; const directPrecept = resolveValidatedPenalPrecept(item.penal_article_id); const conditionalPrecept = resolveValidatedPenalPrecept(conditionalPenal?.penal_article_id); return <article className="sheet"><div className="sheettitle"><div><span className="kicker">FICHA OPERATIVA</span><h2>{item.titulo}</h2></div><button className="copy" onClick={onCopy}>{copied ? "✓ Copiado" : "⧉ Copiar resumen operativo"}</button></div>
  <InfoSection number="1" title="Qué comprobar"><ul>{item.que_comprobar.map((x) => <li key={x}>{x}</li>)}</ul></InfoSection><InfoSection number="2" title="Resultado / posible infracción"><p className="leadresult">{item.resultado}</p></InfoSection>
  <div className="twocol"><InfoSection number="3" title="Norma y codificado"><p><strong>{item.norma} — art. {item.articulo}</strong></p>{item.codificado && <p className="code"><span>Codificado ARCI</span><strong>{item.codificado}</strong></p>}</InfoSection><InfoSection number="4" title="Calificación e importe">{item.calificacion && item.importe_fijo != null ? <p>Infracción <strong>{item.calificacion}</strong>. Importe: <strong>{euro.format(item.importe_fijo)}</strong>{item.importe_reducido != null && <>. Pago con reducción: <strong>{euro.format(item.importe_reducido)}</strong></>}.</p> : item.calificacion && item.rango_min != null && item.rango_max != null ? <p>La norma califica esta conducta como infracción <strong>{item.calificacion}</strong> y prevé una sanción de entre <strong>{euro.format(item.rango_min)} y {euro.format(item.rango_max)}</strong>. La cuantía concreta será determinada por el órgano sancionador competente.</p> : <p>{item.calificacion ? <>La norma califica esta conducta como infracción <strong>{item.calificacion}</strong>. No consta cuantía validada.</> : "La calificación y el importe dependen del supuesto jurídicamente acreditado."}</p>}</InfoSection></div>
  <InfoSection number="5" title="Actuación policial"><ol>{visibleTextList(item.actuacion).map((x) => <li key={x}>{x}</li>)}</ol></InfoSection>{!!linkedMeasures.length && <InfoSection number="6" title="Medidas policiales">{linkedMeasures.map((measure) => <div className="measure" key={measure.id}><strong>{measure.titulo}</strong><p><span>Activación:</span> {measure.activacion}</p>{measure.fundamento && <p><span>Fundamento:</span> {measure.fundamento}</p>}<ul>{measure.actuaciones.map((action) => <li key={action}>{action}</li>)}</ul><p><span>Finalización o levantamiento:</span> {measure.levantamiento}</p></div>)}</InfoSection>}<InfoSection number={linkedMeasures.length ? "7" : "6"} title="Responsable y competencia"><div className="competence"><p><span>Responsable</span>{item.responsable ?? "Según el tipo aplicable"}</p><p><span>Órgano actuante / formulador</span>{item.competencia_denuncia}</p><p><span>Competencia administrativa / órgano sancionador</span>{item.competencia_resuelve}</p></div></InfoSection>
  {!!conditionalFit?.length && <ConditionalSection title="Encaje según el supuesto"><ul>{conditionalFit.map((entry) => <li key={`${entry.supuesto}-${entry.articulo}`}><strong>{entry.supuesto}</strong><span>Art. {entry.articulo} · {entry.calificacion === "sin infracción ITV" ? entry.calificacion : `Infracción ${entry.calificacion}`}{entry.codificado && ` · ${entry.codificado}`}{entry.importe_fijo != null && ` · ${euro.format(entry.importe_fijo)}`}{entry.importe_reducido != null && ` / ${euro.format(entry.importe_reducido)} con reducción`}</span></li>)}</ul></ConditionalSection>}
  {conditionalClassification && <ConditionalSection title="La calificación cambia si..."><p><strong>{conditionalClassification.si}</strong>: infracción <strong>{conditionalClassification.calificacion}</strong>{conditionalClassification.rango_min != null && conditionalClassification.rango_max != null ? <> con rango de <strong>{euro.format(conditionalClassification.rango_min)} a {euro.format(conditionalClassification.rango_max)}</strong></> : null}.</p></ConditionalSection>}
  {!!visibleWarnings.length && <InfoSection number={linkedMeasures.length ? "8" : "7"} title="Advertencias"><div className="notice">{visibleWarnings.map((x) => <p key={x}>{x}</p>)}</div></InfoSection>}
  {conditionalPenal?.activa && conditionalPrecept && <ConditionalPenalActivation relevance={conditionalPenal} active={conditionalPenalActive} onChange={setConditionalPenalActive} precept={conditionalPrecept} destination={item.destino_diligencias_penales} rule={rules.find((candidate) => candidate.id === "GEN-JUR-001" && candidate.activo)} />}
  {item.alerta_penal && directPrecept && <><PenalBlock precept={directPrecept} destination={item.destino_diligencias_penales} actions={[]} />{rule && <NonBisBlock rule={rule} />}</>}
  <details><summary>Fuentes jurídicas ({linkedSources.length})</summary>{linkedSources.map((source) => <p key={source.id}><strong>{source.nombre}</strong>{(source.ambito || source.tipo) && <><br/><span>{[source.ambito, source.tipo].filter(Boolean).join(" · ")}</span></>}</p>)}</details></article> }
function TrafficAmount({ calificacion, amount, reduced, label }: { calificacion?: string | null; amount?: number | null; reduced?: number | null; label?: string }) { return amount != null ? <p>{label && <span>{label}</span>}{calificacion ? <><strong>{calificacion.toUpperCase()}</strong> · </> : null}<strong>{euro.format(amount)}</strong>{reduced != null && <> · con reducción: <strong>{euro.format(reduced)}</strong></>}</p> : <p>{label && <span>{label}</span>}Sin calificación o cuantía autónoma para esta salida.</p> }
function TrafficCaseSheet({ item, copied, onCopy }: { item: OperationalCase; copied: boolean; onCopy: () => void }) {
  const linkedSources = resolveCaseSources(item.fuentes); const visibleWarnings = visibleOperationalWarnings(item); const variants = item.datos_adicionales?.encaje_condicional;
  return <article className={`sheet traffic-sheet ${item.id === "TR-SOA-OP-001" ? "insurance-conventional-sheet" : ""}`}><div className="sheettitle"><div><span className="kicker">FICHA OPERATIVA DE TRÁFICO</span><h2>{item.titulo}</h2></div><button className="copy" onClick={onCopy}>{copied ? "✓ Copiado" : "⧉ Copiar resumen operativo"}</button></div>
    <section className="traffic-primary">
      <div className="traffic-field"><span>1 · INFRACCIÓN OBSERVADA</span><p className="traffic-result">{item.resultado}</p></div>
      {item.es_infraccion_autonoma === false ? <div className="traffic-field non-autonomous"><span>NATURALEZA DE LA FICHA</span><strong>NO ES UNA INFRACCIÓN AUTÓNOMA</strong><p>La denuncia solo puede formularse después de identificar el defecto concreto y su tipo oficial.</p></div> : <>
        <div className="traffic-field"><span>2 · NORMA INFRINGIDA</span><p><strong>{item.norma_infringida} — art. {item.articulo_infringido}</strong></p>{item.tipificacion_norma && item.tipificacion_articulo && <p className="typification"><strong>{item.tipificacion_etiqueta ?? "Tipificación"}:</strong> {item.tipificacion_norma} — art. {item.tipificacion_articulo}</p>}</div>
        {!variants?.length && <div className="traffic-field"><span>3 · TEXTO LITERAL PARA EL BOLETÍN</span><blockquote className="denuncia-literal">{item.textoDenuncia}</blockquote></div>}
        {!variants?.length && <div className="traffic-grid"><div className="traffic-field"><span>4 · CODIFICADO ARCI</span><strong className="arci-code">{item.codificado}</strong></div><div className="traffic-field"><span>5 · CALIFICACIÓN E IMPORTE</span><TrafficAmount calificacion={item.calificacion} amount={item.importe_fijo} reduced={item.importe_reducido} /></div></div>}
      </>}
      {!!variants?.length && <div className="traffic-variants"><span className="field-label">SALIDA SEGÚN EL SUPUESTO</span>{variants.map((entry) => <div className={`traffic-variant ${entry.calificacion === "sin infracción ITV" ? "no-offence" : ""}`} key={`${entry.supuesto}-${entry.articulo}`}><h3>{entry.supuesto}</h3>{entry.calificacion === "sin infracción ITV" ? <p><strong>SIN INFRACCIÓN ITV</strong></p> : <><p><strong>{entry.norma_infringida} — art. {entry.articulo_infringido}</strong></p>{entry.tipificacion_norma && <p className="typification"><strong>{entry.tipificacion_etiqueta ?? "Tipificación"}:</strong> {entry.tipificacion_norma} — art. {entry.tipificacion_articulo}</p>}<span className="field-label">3 · TEXTO LITERAL PARA EL BOLETÍN</span><blockquote className="denuncia-literal">{entry.textoDenuncia}</blockquote><div className="variant-facts"><p><span>4 · CODIFICADO ARCI</span><strong>{entry.codificado}</strong></p><TrafficAmount label="5 · CALIFICACIÓN E IMPORTE" calificacion={entry.calificacion} amount={entry.importe_fijo} reduced={entry.importe_reducido} /></div></>}</div>)}</div>}
      <div className="traffic-field"><span>6 · RESPONSABLE</span><p><strong>{item.responsable ?? "Según el tipo aplicable"}</strong></p></div>
      <div className="traffic-field"><span>ACTUACIÓN POLICIAL BREVE</span><ul>{visibleTextList(item.actuacion_breve ?? item.actuacion).map((action) => <li key={action}>{action}</li>)}</ul></div>
    </section>
    <details className="traffic-secondary"><summary>Comprobaciones y actuación ampliada</summary><h3>Qué comprobar</h3><ul>{item.que_comprobar.map((check) => <li key={check}>{check}</li>)}</ul><h3>Actuación ampliada</h3><ol>{visibleTextList(item.actuacion).map((action) => <li key={action}>{action}</li>)}</ol><div className="competence"><p><span>Órgano actuante / formulador</span>{item.competencia_denuncia}</p>{item.competencia_instruye && <p><span>Receptor / instructor</span>{item.competencia_instruye}</p>}<p><span>Órgano sancionador</span>{item.competencia_resuelve}</p></div></details>
    {item.estado_circulacion && <section className="traffic-circulation"><h3>ESTADO DE CIRCULACIÓN</h3><strong>{item.estado_circulacion}</strong></section>}
    {item.medida_operativa && <TrafficMeasureSummary plan={item.medida_operativa} />}
    {!!visibleWarnings.length && <details className="traffic-secondary"><summary>Advertencias</summary><div className="notice">{visibleWarnings.map((warning) => <p key={warning}>{warning}</p>)}</div></details>}
    <details className="traffic-secondary"><summary>Fuentes jurídicas ({linkedSources.length})</summary>{linkedSources.map((source) => <p key={source.id}><strong>{source.nombre}</strong>{(source.ambito || source.tipo) && <><br/><span>{[source.ambito, source.tipo].filter(Boolean).join(" · ")}</span></>}</p>)}</details>
  </article>
}
function TrafficMeasureSummary({ plan }: { plan: TrafficMeasurePlan }) {
  const item = (label: string, status: string | undefined, fundamento: string | undefined, detail: string) => <section key={label}><span>{label}{status ? ` — ${status}` : ""}</span><p>{fundamento && <><strong>{fundamento}</strong>{" · "}</>}{detail}</p></section>;
  return <section className="traffic-vehicle-measure"><h3>MEDIDA SOBRE EL VEHÍCULO</h3><div>{plan.circulacion && item("CIRCULACIÓN", plan.circulacion.estado, plan.circulacion.fundamento, plan.circulacion.detalle)}{item("INMOVILIZACIÓN", plan.inmovilizacion.estado, plan.inmovilizacion.fundamento, plan.inmovilizacion.detalle)}{plan.lugar_inmovilizacion && item("LUGAR DE INMOVILIZACIÓN", undefined, plan.lugar_inmovilizacion.fundamento, plan.lugar_inmovilizacion.detalle)}{plan.traslado_deposito && item("TRASLADO A DEPÓSITO", plan.traslado_deposito.estado, plan.traslado_deposito.fundamento, plan.traslado_deposito.detalle)}{plan.alternativas_inmovilizacion?.map((condition) => item("CAUSA CONCRETA", undefined, condition.fundamento, condition.detalle))}{plan.regimen_especifico && item("RÉGIMEN ESPECÍFICO DEL SEGURO", undefined, plan.regimen_especifico.fundamento, plan.regimen_especifico.detalle)}{plan.regla_sectorial && item("REGLA SECTORIAL", undefined, undefined, plan.regla_sectorial)}{plan.retirada_sin_lugar && item("ADEMÁS, SI NO EXISTE LUGAR ADECUADO", undefined, plan.retirada_sin_lugar.fundamento, plan.retirada_sin_lugar.detalle)}{plan.retirada_persistencia && item("SI LA CAUSA NO CESA", undefined, plan.retirada_persistencia.fundamento, plan.retirada_persistencia.detalle)}{plan.levantamiento && item("LEVANTAMIENTO", undefined, undefined, plan.levantamiento)}</div></section>;
}
function InfoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="infosection"><h3><span>{number}</span>{title}</h3><div>{children}</div></section> }
function ConditionalSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="conditional"><h3>{title}</h3>{children}</section> }
export function ConditionalPenalActivation({ relevance, active, onChange, precept, destination, rule }: { relevance: ConditionalPenalRelevance; active: boolean; onChange: (active: boolean) => void; precept: PenalPrecept; destination?: string | null; rule?: { nombre: string; contenido: string } }) { return <section className="penal-activation"><h3>Advertencia de escalado</h3><p>{relevance.titulo}</p><ul>{visibleTextList(relevance.condiciones).map((condition) => <li key={condition}>{condition}</li>)}</ul><label><input type="checkbox" checked={active} onChange={(event) => onChange(event.target.checked)} /> Confirmo que concurren los hechos descritos</label>{active && <><PenalBlock precept={precept} destination={destination} actions={relevance.accion} />{rule && <NonBisBlock rule={rule} />}</>}</section> }
export function PenalBlock({ precept, destination, actions }: { precept: PenalPrecept; destination?: string | null; actions: string[] }) { const visibleActions = visibleTextList(actions); return <section className="penal"><span>⚠</span><div><h3>POSIBLE RELEVANCIA PENAL</h3><strong>{precept.norma}, artículo {precept.articulo}</strong><h4>TEXTO DEL ARTÍCULO</h4><p className="penal-literal">{precept.texto_literal}</p><h4>ACTUACIÓN PENAL</h4>{visibleActions.length > 0 && <ol>{visibleActions.map((action) => <li key={action}>{action}</li>)}</ol>}{destination && <p className="penal-destination"><strong>Destino de las diligencias penales:</strong> {destination}</p>}</div></section> }
function NonBisBlock({ rule }: { rule: { nombre: string; contenido: string } }) { if (containsInternalInterfaceLanguage(`${rule.nombre} ${rule.contenido}`)) return null; return <section className="nonbis"><h3>{rule.nombre}</h3><p>{rule.contenido}</p></section> }
