"use client";
import { useMemo, useState } from "react";
import { modules } from "@/data/modules";
import { categories } from "@/data/categories";
import { cases } from "@/data/cases";
import { rules } from "@/data/rules";
import { resolveCaseSources } from "@/data/sources";
import type { OperationalCase } from "@/data/types";
type View = { moduleId?: string; categoryId?: string; caseId?: string };
const euro = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" });
const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export default function Home() {
  const [view, setView] = useState<View>({}); const [query, setQuery] = useState(""); const [copied, setCopied] = useState(false);
  const validCases = useMemo(() => cases.filter((item) => item.estado === "validado"), []);
  const selectedModule = modules.find((item) => item.id === view.moduleId); const selectedCategory = categories.find((item) => item.id === view.categoryId); const selectedCase = validCases.find((item) => item.id === view.caseId);
  const results = useMemo(() => { const q = normalize(query.trim()); if (!q) return []; return validCases.filter((item) => normalize([item.titulo, ...item.palabras_clave, item.modulo, item.categoria, item.norma, item.articulo].join(" ")).includes(q)); }, [query, validCases]);
  const openCase = (item: OperationalCase) => { setView({ moduleId: item.modulo, categoryId: item.categoria, caseId: item.id }); setQuery(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const goBack = () => setView(selectedCase ? { moduleId: view.moduleId, categoryId: view.categoryId } : selectedCategory ? { moduleId: view.moduleId } : {});
  const copySummary = async (item: OperationalCase) => { const range = item.rango_min != null && item.rango_max != null ? `${item.calificacion}: ${euro.format(item.rango_min)} – ${euro.format(item.rango_max)}` : item.calificacion ?? "Sin rango validado"; const text = `${item.titulo}\n${item.resultado}\n${item.norma} — art. ${item.articulo}\n${range}\nActuación: ${item.actuacion.join(" ")}\nCompetencia: ${item.competencia_denuncia} ${item.competencia_resuelve}`; await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <main><header className="topbar"><div className="brandmark">BO</div><div><span className="eyebrow">PROTOTIPO V0.3</span><h1>Base Operativa <span>Policía Local</span></h1></div></header><div className="shell">
    {(selectedModule || selectedCategory || selectedCase) && <button className="back" onClick={goBack}>← Volver</button>}
    {!selectedCase && <section className="searchbox"><label htmlFor="search">Consulta rápida</label><div className="searchrow"><span>⌕</span><input id="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por caso, palabra clave, norma o artículo…" autoComplete="off" />{query && <button onClick={() => setQuery("")} aria-label="Borrar búsqueda">×</button>}</div>{query && <div className="results"><p>{results.length ? `${results.length} resultado${results.length > 1 ? "s" : ""}` : "No hay casos validados que coincidan"}</p>{results.map((item) => <button key={item.id} onClick={() => openCase(item)}><span><strong>{item.titulo}</strong><small>{modules.find((m) => m.id === item.modulo)?.nombre} · {categories.find((c) => c.id === item.categoria)?.nombre}</small></span><b>›</b></button>)}</div>}</section>}
    {!selectedModule && !query && <section><div className="intro"><p>Selecciona un ámbito de actuación</p><span>El contenido se genera desde una base común de datos estructurados.</span></div><div className="modulegrid">{modules.filter((m) => m.activo).sort((a,b) => a.orden-b.orden).map((m, i) => { const count = validCases.filter((c) => c.modulo === m.id).length; return <button className="modulecard" key={m.id} onClick={() => setView({ moduleId: m.id })}><span className={`moduleicon tone-${i}`}>{["◉","◇","▥","⬡"][i]}</span><span><strong>{m.nombre}</strong><small>{m.descripcion}</small><em>{count ? `${count} casos disponibles` : "Contenido en desarrollo"}</em></span><b>›</b></button>})}</div></section>}
    {selectedModule && !selectedCategory && <section><div className="sectionhead"><span className="kicker">MÓDULO</span><h2>{selectedModule.nombre}</h2><p>{selectedModule.descripcion}</p></div>{categories.some((c) => c.modulo === selectedModule.id && c.activo) ? <div className="listcards">{categories.filter((c) => c.modulo === selectedModule.id && c.activo).sort((a,b) => a.orden-b.orden).map((c) => { const count = validCases.filter((item) => item.categoria === c.id).length; return <button key={c.id} onClick={() => setView({ moduleId: selectedModule.id, categoryId: c.id })}><span><strong>{c.nombre}</strong><small>{c.descripcion}</small></span><em>{count} {count === 1 ? "caso" : "casos"}</em><b>›</b></button>})}</div> : <Empty text="La arquitectura del módulo ya está preparada para incorporar categorías y casos validados." />}</section>}
    {selectedCategory && !selectedCase && <section><div className="sectionhead"><span className="kicker">{selectedModule?.nombre}</span><h2>{selectedCategory.nombre}</h2><p>{selectedCategory.descripcion}</p></div><div className="listcards">{validCases.filter((item) => item.categoria === selectedCategory.id).map((item) => <button key={item.id} onClick={() => openCase(item)}><span><strong>{item.titulo}</strong><small>{item.norma} · art. {item.articulo}</small></span>{item.alerta_penal && <em className="warningtag">Atención penal</em>}<b>›</b></button>)}</div>{!validCases.some((item) => item.categoria === selectedCategory.id) && <Empty title="Sin casos validados" text="Los casos en borrador, revisión o bloqueados no se muestran como utilizables." />}</section>}
    {selectedCase && <CaseSheet item={selectedCase} copied={copied} onCopy={() => copySummary(selectedCase)} />}
  </div><footer><strong>Herramienta de apoyo.</strong> Verificar siempre la normativa vigente y las circunstancias concretas.</footer></main>;
}
function Empty({ title="Contenido en desarrollo", text }: { title?: string; text: string }) { return <div className="empty"><h3>{title}</h3><p>{text}</p></div> }
export function CaseSheet({ item, copied, onCopy }: { item: OperationalCase; copied: boolean; onCopy: () => void }) { const rule = rules.find((r) => r.id === item.regla_transversal && r.activo); const linkedSources = resolveCaseSources(item.fuentes); return <article className="sheet"><div className="sheettitle"><div><span className="kicker">FICHA OPERATIVA · {item.id}</span><h2>{item.titulo}</h2></div><button className="copy" onClick={onCopy}>{copied ? "✓ Copiado" : "⧉ Copiar resumen operativo"}</button></div>
  <InfoSection number="1" title="Qué comprobar"><ul>{item.que_comprobar.map((x) => <li key={x}>{x}</li>)}</ul></InfoSection><InfoSection number="2" title="Resultado / posible infracción"><p className="leadresult">{item.resultado}</p></InfoSection>
  <div className="twocol"><InfoSection number="3" title="Norma"><p><strong>{item.norma} — art. {item.articulo}</strong></p></InfoSection><InfoSection number="4" title="Calificación y rango sancionador">{item.calificacion && item.rango_min != null && item.rango_max != null ? <p>La norma califica esta conducta como infracción <strong>{item.calificacion}</strong> y prevé una sanción de entre <strong>{euro.format(item.rango_min)} y {euro.format(item.rango_max)}</strong>. La cuantía concreta será determinada por el órgano sancionador competente.</p> : <p>{item.calificacion ? <>La norma califica esta conducta como infracción <strong>{item.calificacion}</strong>. No consta un rango sancionador vigente validado.</> : "No consta calificación ni rango sancionador validados en este caso."}</p>}</InfoSection></div>
  <InfoSection number="5" title="Actuación policial"><ol>{item.actuacion.map((x) => <li key={x}>{x}</li>)}</ol></InfoSection><InfoSection number="6" title="Competencia"><div className="competence"><p><span>Comprobación / denuncia</span>{item.competencia_denuncia}</p><p><span>Órgano sancionador / resolución</span>{item.competencia_resuelve}</p></div></InfoSection>
  {!!item.advertencias.length && <InfoSection number="7" title="Advertencias"><div className="notice">{item.advertencias.map((x) => <p key={x}>{x}</p>)}</div></InfoSection>}{item.alerta_penal && <section className="penal"><span>⚠</span><div><h3>Posible relevancia penal</h3><p>{item.referencia_penal}</p>{rule && <><strong>{rule.nombre}</strong><p>{rule.contenido}</p></>}</div></section>}
  <details><summary>Fuentes jurídicas ({linkedSources.length})</summary>{linkedSources.map((source) => <p key={source.id}><strong>{source.nombre}</strong>{(source.ambito || source.tipo) && <><br/><span>{[source.ambito, source.tipo].filter(Boolean).join(" · ")}</span></>}</p>)}</details></article> }
function InfoSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="infosection"><h3><span>{number}</span>{title}</h3><div>{children}</div></section> }
